build:
  version: "1.0"

cards:
  message: "Welcome to Evil Ass Banking - Cards API"
  contactDetails:
    name: "Edu Romero - Lead Developer"
    email: "edu@romero.com"
  onCallSupport:
    - +34 654321987
    - +34 654987321